import { test, expect, type Page } from "@playwright/test"

async function loginOwner(page: Page) {
  await page.goto("/auth/login", { waitUntil: "domcontentloaded" })
  await expect(page.locator("#identifier")).toBeFocused({ timeout: 15_000 })
  await page.locator("#identifier").fill("demo@multi-pos.com")
  await page.locator("#password").fill("demo1234")
  await page.getByRole("button", { name: /^entrar/i }).click()
  await page.waitForURL((url) => url.pathname.startsWith("/admin"), { timeout: 45_000, waitUntil: "domcontentloaded" })
}

async function loginPortal(page: Page) {
  await page.goto("/portal/auth/login", { waitUntil: "domcontentloaded" })
  await expect(page.getByTestId("app-splash")).toBeHidden({ timeout: 10_000 })
  await expect(page.locator("#identifier")).toBeFocused({ timeout: 15_000 })
  await page.locator("#identifier").fill("hcli-001@hibrido.local")
  await page.locator("#password").fill("demo1234")
  await page.getByRole("button", { name: /^entrar/i }).click()
  await page.waitForURL((url) => url.pathname === "/portal", { timeout: 45_000, waitUntil: "domcontentloaded" })
}

test("proveedor: foco inicial y Enter guarda el formulario", async ({ page }, testInfo) => {
  await loginOwner(page)
  await page.goto("/admin/purchasing", { waitUntil: "domcontentloaded" })
  await page.getByRole("button", { name: "Nuevo proveedor" }).click()
  await expect(page.locator("#supplier-name")).toBeFocused()
  await page.locator("#supplier-name").press("Enter")
  await expect(page.locator("#supplier-name")).toHaveAttribute("aria-invalid", "true")
  await expect(page.locator("#supplier-name")).toBeFocused()
  const name = `Proveedor UX ${testInfo.project.name} ${Date.now()}`
  await page.locator("#supplier-name").fill(name)
  await page.locator("#supplier-name").press("Enter")
  await expect(page.getByRole("dialog", { name: "Nuevo proveedor" })).toBeHidden({ timeout: 30_000 })
  await expect(page.getByText(name, { exact: true })).toBeVisible({ timeout: 30_000 })
  await page.screenshot({ path: testInfo.outputPath("proveedor-guardado.png"), fullPage: true })
})

test("compras: cotización y orden validan por Enter y conservan los totales", async ({ page }, testInfo) => {
  await loginOwner(page)
  await page.goto("/admin/purchasing", { waitUntil: "domcontentloaded" })
  await page.getByRole("tab", { name: "Cotizaciones" }).click()
  await page.getByRole("button", { name: "Nueva cotización" }).click()
  const dialog = page.getByRole("dialog", { name: "Nueva solicitud de cotización" })
  await expect(dialog).toBeVisible()
  await dialog.getByRole("button", { name: "Crear cotización" }).click()
  await expect(page.locator("#purchase-supplier")).toHaveAttribute("aria-invalid", "true")
  await expect(page.locator("#purchase-supplier")).toBeFocused()
  await expect(page.locator("#purchase-add-product")).toHaveAttribute("aria-invalid", "true")
  await page.locator("#purchase-supplier").click()
  await page.locator("[cmdk-item]").first().click()
  await page.locator("#purchase-add-product").click()
  await page.locator("[cmdk-item]").first().click()
  await expect(dialog.locator('input[id^="qty-"]').first()).toBeVisible()
  await dialog.locator('input[id^="qty-"]').first().fill("2")
  await dialog.locator('input[id^="cost-"]').first().fill("12.50")
  await dialog.locator('input[id^="tax-"]').first().fill("0.16")
  await expect(dialog.getByText(/Total estimado:.*29/)).toBeVisible()
  const quoteResponsePromise = page.waitForResponse((response) => response.url().endsWith("/api/purchasing") && response.request().method() === "POST" && response.request().postData()?.includes('"quote.create"') === true)
  await dialog.locator('input[id^="qty-"]').first().press("Enter")
  const quoteResponse = await quoteResponsePromise
  expect(quoteResponse.ok()).toBe(true)
  const quote = (await quoteResponse.json()).data as { folio: string }
  await expect(dialog).toBeHidden({ timeout: 30_000 })
  const quoteRow = page.locator("div.rounded-xl.border.p-4").filter({ has: page.getByText(quote.folio, { exact: true }) })
  await expect(quoteRow).toBeVisible({ timeout: 30_000 })
  await quoteRow.getByRole("button", { name: "Crear orden" }).click()
  const orderDialog = page.getByRole("dialog", { name: "Nueva orden de compra" })
  await orderDialog.getByRole("button", { name: "Crear orden" }).click()
  await expect(page.locator("#purchase-target")).toHaveAttribute("aria-invalid", "true")
  await expect(page.locator("#purchase-target")).toBeFocused()
  await page.locator("#purchase-target").click()
  await page.locator("[cmdk-item]").first().click()
  await expect(orderDialog.getByText(/Total estimado:.*29/)).toBeVisible()
  const orderResponsePromise = page.waitForResponse((response) => response.url().endsWith("/api/purchasing") && response.request().method() === "POST" && response.request().postData()?.includes('"order.create"') === true)
  await orderDialog.locator('input[id^="qty-"]').first().press("Enter")
  const orderResponse = await orderResponsePromise
  expect(orderResponse.ok()).toBe(true)
  const order = (await orderResponse.json()).data as { total: string | number; folio: string }
  expect(Number(order.total)).toBeCloseTo(29, 2)
  await expect(orderDialog).toBeHidden({ timeout: 30_000 })
  await page.getByRole("tab", { name: "Órdenes" }).click()
  const orderCard = page.locator('[data-slot="card"]').filter({ has: page.getByText(order.folio, { exact: true }) })
  await expect(orderCard).toBeVisible({ timeout: 30_000 })
  await expect(orderCard.getByText("$29.00")).toBeVisible()
  await orderCard.getByRole("button", { name: "Aprobar" }).click()
  await expect(orderCard.getByRole("button", { name: "Recibir" })).toBeVisible({ timeout: 30_000 })
  await orderCard.getByRole("button", { name: "Recibir" }).click()
  const receiveDialog = page.getByRole("dialog", { name: `Recibir ${order.folio}` })
  await receiveDialog.locator('input[id^="receive-"]').first().fill("1")
  const receiptResponsePromise = page.waitForResponse((response) => response.url().endsWith("/api/purchasing") && response.request().method() === "POST" && response.request().postData()?.includes('"receive"') === true)
  await receiveDialog.getByRole("button", { name: "Confirmar recepción" }).click()
  expect((await receiptResponsePromise).ok()).toBe(true)
  await expect(receiveDialog).toBeHidden({ timeout: 30_000 })
  await expect(orderCard.getByText(/Recibido: 1 de 2 unidades/)).toBeVisible({ timeout: 30_000 })
  await page.screenshot({ path: testInfo.outputPath("orden-recepcion-parcial.png"), fullPage: true })
})

test("publicación: Enter muestra errores y conserva el foco", async ({ page }, testInfo) => {
  await loginOwner(page)
  await page.goto("/admin/publications", { waitUntil: "domcontentloaded" })
  await page.getByRole("button", { name: "Nueva publicación" }).click()
  const title = page.locator("#publication-title")
  await expect(title).toBeFocused()
  await title.press("Enter")
  await expect(title).toBeFocused()
  await expect(title).toHaveAttribute("aria-invalid", "true")
  await expect(page.getByRole("dialog", { name: "Nueva publicación" })).toBeVisible()
  await title.fill("Aviso de prueba")
  await page.getByLabel("Color primario del flyer").fill("#123456")
  await expect(page.getByLabel("Color primario del flyer")).toHaveValue("#123456")
  await page.screenshot({ path: testInfo.outputPath("publicacion-validacion.png"), fullPage: true })
})

test("producto: Enter destaca campos inválidos y enfoca el primero", async ({ page }, testInfo) => {
  await loginOwner(page)
  await page.goto("/admin/products", { waitUntil: "domcontentloaded" })
  await page.getByRole("button", { name: /^nuevo$/i }).click()
  const name = page.locator("#product-name")
  await expect(page.locator("#product-form")).toBeVisible()
  await name.focus()
  await name.press("Enter")
  await expect(name).toBeFocused()
  await expect(name).toHaveAttribute("aria-invalid", "true")
  await expect(page.locator('[data-slot="dialog-content"] [aria-invalid="true"]').first()).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath("producto-validacion.png"), fullPage: true })
})

test("portal: Enter en login vacío muestra errores sin desbordamiento", async ({ page }, testInfo) => {
  await page.goto("/portal/auth/login", { waitUntil: "domcontentloaded" })
  await expect(page.getByTestId("app-splash")).toBeHidden({ timeout: 10_000 })
  const first = page.locator("#identifier")
  await expect(first).toBeFocused()
  await first.press("Enter")
  await expect(first).toBeFocused()
  await expect(first).toHaveAttribute("aria-invalid", "true")
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)
  expect(overflow).toBe(false)
  await page.screenshot({ path: testInfo.outputPath("portal-login-validacion.png"), fullPage: true })
})

test("portal: detalle de producto, carrito y pago conservan la navegación", async ({ page }, testInfo) => {
  await loginPortal(page)
  await page.goto("/portal/store", { waitUntil: "domcontentloaded" })
  const skipTour = page.getByRole("button", { name: "Saltar" })
  await expect(skipTour).toBeVisible({ timeout: 15_000 })
  await skipTour.click()
  await expect(skipTour).toBeHidden()
  const productLink = page.locator('a[href^="/portal/store/"]').first()
  await expect(productLink).toBeVisible({ timeout: 30_000 })
  await productLink.locator("p").first().click()
  await expect(page).toHaveURL(/\/portal\/store\/[^/]+/, { timeout: 30_000 })
  await expect(page.locator("h1")).toBeVisible()
  await expect(page.getByRole("button", { name: "Agregar al carrito" })).toBeVisible()
  await page.getByRole("button", { name: "Agregar al carrito" }).click()
  await page.getByRole("button", { name: "Carrito" }).click()
  const slideToCheckout = page.getByRole("button", { name: "Desliza para pagar" })
  await slideToCheckout.focus()
  await slideToCheckout.press("Enter")
  await expect(page).toHaveURL(/\/portal\/checkout/, { timeout: 30_000 })
  await expect(page.getByRole("heading", { name: "Método de pago" })).toBeVisible({ timeout: 30_000 })
  await expect(page.locator("#pay-credit")).toBeVisible()
  const confirmButton = page.getByRole("button", { name: /Confirmar pedido/ })
  await expect(confirmButton).toBeVisible()
  const buttonBox = await confirmButton.boundingBox()
  const navBox = await page.locator("nav.fixed").boundingBox()
  expect(buttonBox && navBox && buttonBox.y + buttonBox.height <= navBox.y + 1, "la barra inferior no debe tapar la acción de pago").toBe(true)
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)
  expect(overflow).toBe(false)
  await page.screenshot({ path: testInfo.outputPath("portal-checkout.png"), fullPage: true })
})
