export const BULK_CATEGORY_PRESETS: Record<string, readonly string[]> = {
  "Abarrotes / tiendita": [
    "Aceites y mantecas", "Agua", "Alimentos instantáneos", "Arroz", "Artículos desechables",
    "Azúcar y endulzantes", "Bebidas deportivas", "Bebidas energéticas", "Botanas", "Café",
    "Cereales", "Cervezas", "Chocolates", "Condimentos", "Conservas", "Dulces", "Enlatados",
    "Especias", "Frijoles y legumbres", "Galletas", "Harinas", "Higiene bucal", "Higiene femenina",
    "Higiene personal", "Huevo", "Jugos y néctares", "Lácteos", "Leche", "Licores", "Limpieza de cocina",
    "Limpieza del hogar", "Mascotas", "Mayonesa y aderezos", "Pan de caja", "Panadería", "Papel higiénico",
    "Pastas", "Productos para bebé", "Refrescos", "Salsas", "Servilletas", "Sopas", "Té e infusiones",
    "Utensilios domésticos", "Vinos", "Verduras en conserva", "Carnes frías", "Congelados", "Repostería", "Recargas y servicios",
  ],
  "Ferretería": [
    "Abrasivos", "Adhesivos", "Alambres", "Brocas", "Cadenas", "Candados", "Cerraduras", "Cintas",
    "Clavos", "Compresores", "Conexiones hidráulicas", "Cuerdas", "Discos de corte", "Electricidad",
    "Escaleras", "Extensiones eléctricas", "Fijación", "Grifería", "Herramientas de corte", "Herramientas de jardín",
    "Herramientas eléctricas", "Herramientas manuales", "Iluminación", "Impermeabilizantes", "Interruptores y contactos",
    "Jardinería", "Lijas", "Madera", "Mangueras", "Material de construcción", "Medición", "Pegamentos",
    "Pinturas", "Plomería", "Protección personal", "Químicos", "Rodamientos", "Selladores", "Señalización",
    "Soldadura", "Taquetes", "Tornillería", "Tubos y perfiles", "Válvulas", "Ventilación", "Accesorios automotrices",
    "Herrajes", "Organización de herramientas", "Sanitarios", "Equipos de carga",
  ],
  "Carnicería": [
    "Res", "Cerdo", "Pollo", "Pavo", "Cordero", "Cabrito", "Conejo", "Pescados", "Mariscos", "Carne molida",
    "Cortes premium", "Cortes para asar", "Bisteces", "Costillas", "Chuletas", "Filetes", "Vísceras", "Huesos y caldos",
    "Embutidos", "Jamones", "Salchichas", "Chorizos", "Tocino", "Carnes frías", "Marinados", "Adobados",
    "Empanizados", "Preparados", "Hamburguesas", "Brochetas", "Congelados", "Paquetes familiares", "Paquetes para asar",
    "Mayoreo", "Quesos", "Lácteos", "Huevos", "Salsas", "Especias", "Carbón", "Leña", "Desechables",
    "Complementos", "Verduras", "Tortillas", "Pan para hamburguesa", "Bebidas", "Hielo", "Mascotas", "Temporada",
  ],
  "Restaurante": [
    "Entradas", "Ensaladas", "Sopas y caldos", "Platos fuertes", "Especialidades", "Desayunos", "Comidas", "Cenas",
    "Menú infantil", "Hamburguesas", "Pizzas", "Tacos", "Tortas", "Sándwiches", "Pastas", "Mariscos", "Carnes",
    "Pollo", "Vegetariano", "Vegano", "Guarniciones", "Postres", "Panadería", "Helados", "Bebidas frías",
    "Bebidas calientes", "Café", "Té", "Jugos", "Refrescos", "Coctelería", "Cervezas", "Vinos", "Licores",
    "Combos", "Paquetes familiares", "Promociones", "Extras", "Salsas", "Toppings", "Ingredientes adicionales",
    "Para compartir", "Para llevar", "Temporada", "Platillo del día", "Catering", "Eventos", "Productos empacados",
    "Sin gluten", "Bajo en calorías",
  ],
  "Farmacia": [
    "Analgésicos", "Antigripales", "Antiinflamatorios", "Antialérgicos", "Digestivos", "Dermatológicos", "Oftálmicos",
    "Respiratorios", "Vitaminas", "Suplementos", "Primeros auxilios", "Curación", "Material médico", "Ortopedia",
    "Cuidado de heridas", "Cuidado personal", "Higiene bucal", "Higiene femenina", "Higiene íntima", "Dermocosmética",
    "Cuidado facial", "Cuidado corporal", "Cuidado capilar", "Protección solar", "Bebé", "Maternidad", "Pañales",
    "Nutrición infantil", "Adulto mayor", "Incontinencia", "Diabetes", "Monitoreo de salud", "Presión arterial",
    "Termómetros", "Salud sexual", "Planificación familiar", "Productos naturales", "Homeopatía", "Medicamentos genéricos",
    "Medicamentos de patente", "Medicamentos con receta", "Venta libre", "Refrigerados", "Equipos de movilidad",
    "Cubrebocas y protección", "Repelentes", "Alimentos saludables", "Bebidas hidratantes", "Óptica", "Servicios farmacéuticos",
  ],
  "Papelería": [
    "Cuadernos", "Libretas", "Hojas", "Papel especializado", "Cartulinas", "Escritura", "Lápices", "Bolígrafos",
    "Marcadores", "Colores", "Escolar", "Oficina", "Archivo", "Organización", "Carpetas", "Sobres", "Etiquetas",
    "Adhesivos", "Cintas", "Tijeras y corte", "Geometría", "Calculadoras", "Arte", "Pintura artística", "Pinceles",
    "Manualidades", "Foamy", "Decoración", "Regalos", "Envolturas", "Fiesta", "Didácticos", "Juegos de mesa",
    "Libros", "Lectura infantil", "Impresión", "Copias", "Engargolado", "Enmicado", "Sellos", "Tinta y tóner",
    "Accesorios de cómputo", "Memorias USB", "Cables", "Mobiliario escolar", "Mochilas", "Loncheras", "Uniformes",
    "Temporada escolar", "Servicios digitales",
  ],
  "Ropa": [
    "Dama", "Caballero", "Niñas", "Niños", "Bebé", "Unisex", "Blusas", "Camisas", "Playeras", "Pantalones",
    "Jeans", "Shorts", "Faldas", "Vestidos", "Trajes", "Conjuntos", "Chamarras", "Suéteres", "Sudaderas", "Abrigos",
    "Ropa interior", "Pijamas", "Trajes de baño", "Ropa deportiva", "Ropa de trabajo", "Uniformes", "Maternidad",
    "Tallas extra", "Calzado", "Tenis", "Sandalias", "Botas", "Tacones", "Bolsas", "Carteras", "Cinturones",
    "Sombreros y gorras", "Bufandas", "Lentes", "Joyería", "Relojes", "Accesorios", "Calcetines", "Medias",
    "Temporada", "Fiesta", "Formal", "Casual", "Liquidación", "Nuevas colecciones",
  ],
  "Mascotas": [
    "Alimento para perros", "Alimento para gatos", "Alimento para aves", "Alimento para peces", "Alimento para roedores",
    "Alimento húmedo", "Alimento seco", "Dietas especiales", "Premios", "Huesos y carnazas", "Suplementos", "Farmacia veterinaria",
    "Antipulgas", "Desparasitación", "Higiene", "Shampoo", "Cepillos", "Cuidado dental", "Arena para gatos", "Areneros",
    "Pañales", "Camas", "Casas", "Transportadoras", "Jaulas", "Peceras", "Comederos", "Bebederos", "Collares",
    "Correas", "Arneses", "Placas", "Ropa", "Juguetes", "Entrenamiento", "Limpieza", "Control de olores",
    "Estética canina", "Baño", "Consulta veterinaria", "Vacunación", "Aves", "Acuarios", "Roedores", "Reptiles",
    "Perros", "Gatos", "Accesorios de viaje", "Adopción", "Temporada",
  ],
  "Autolavado": [
    "Lavado exterior", "Lavado interior", "Lavado completo", "Lavado express", "Lavado ecológico", "Lavado de motor",
    "Lavado de chasis", "Lavado de vestiduras", "Lavado de alfombras", "Detallado exterior", "Detallado interior",
    "Detallado premium", "Encerado", "Pulido", "Abrillantado", "Descontaminado de pintura", "Corrección de pintura",
    "Recubrimiento cerámico", "Sellado de pintura", "Restauración de faros", "Limpieza de rines", "Limpieza de llantas",
    "Limpieza de cristales", "Tratamiento de parabrisas", "Sanitización", "Desodorización", "Aspirado", "Vapor",
    "Lavado de tapicería", "Protección de interiores", "Hidratación de piel", "Paquetes básicos", "Paquetes premium",
    "Membresías", "Flotillas", "Motocicletas", "Camionetas", "Vehículos grandes", "Servicio a domicilio", "Recolección y entrega",
    "Aromatizantes", "Microfibras", "Ceras", "Shampoo automotriz", "Limpiadores", "Accesorios automotrices",
    "Promociones", "Extras", "Inspección visual", "Temporada",
  ],
  "Servicios": [
    "Consultoría", "Asesoría", "Diagnóstico", "Instalación", "Mantenimiento preventivo", "Mantenimiento correctivo",
    "Reparación", "Soporte técnico", "Visita a domicilio", "Servicio urgente", "Cita en sucursal", "Evaluación inicial",
    "Presupuesto", "Paquetes", "Planes mensuales", "Suscripciones", "Servicios empresariales", "Servicios residenciales",
    "Capacitación", "Talleres", "Cursos", "Sesiones individuales", "Sesiones grupales", "Seguimiento", "Renovación",
    "Garantías", "Refacciones", "Materiales", "Insumos", "Consumibles", "Renta de equipo", "Mano de obra",
    "Traslado", "Entrega", "Recolección", "Configuración", "Personalización", "Diseño", "Producción", "Revisión",
    "Certificación", "Trámites", "Eventos", "Reservaciones", "Promociones", "Complementos", "Servicios digitales",
    "Atención remota", "Atención presencial", "Otros servicios",
  ],
}

