// FASE 1.5 — Tipos TypeScript derivados del schema Prisma.
// Re-exporta solo tipos (sin PrismaClient) para no inflar bundles de cliente.

export type {
  AppSettings,
  CashRegister,
  CashSession,
  Category,
  Cedi,
  CompanyProfile,
  Coupon,
  Customer,
  CustomerFavorite,
  CustomerPaymentMethod,
  Employee,
  EmployeePosition,
  Inventory,
  InventoryMovement,
  InventoryRevision,
  InventoryRevisionItem,
  Location,
  LoyaltyTransaction,
  Membership,
  Notification,
  Order,
  OrderItem,
  OrderPreparation,
  OrderPreparationItem,
  OrderStatusHistory,
  Organization,
  Permission,
  Product,
  ProductOption,
  ProductOptionValue,
  ProductVariant,
  Profile,
  Promotion,
  PromotionTarget,
  Publication,
  Role,
  RolePermission,
  Sale,
  SaleDiscount,
  SaleItem,
  SalePayment,
  ShoppingList,
  ShoppingListItem,
  UnitOfMeasure,
  User,
  UserInvitation,
  VariantOptionValue,
  VariantPriceHistory,
} from "@prisma/client";

export type {
  CashSessionStatus,
  DeliveryMethod,
  LocationType,
  LoyaltyKind,
  MovementType,
  OrderStatus,
  OrgRole,
  PaymentMethod,
  ProductType,
  PromoBenefit,
  PromoScope,
  PromotionTargetKind,
  PublicationType,
  RevisionStatus,
  SaleStatus,
} from "@prisma/client";

import { Prisma } from "@prisma/client";
export { Prisma };
