CREATE TABLE `point_payment_intents` (
  `id` VARCHAR(191) NOT NULL,
  `organizationId` VARCHAR(191) NOT NULL,
  `locationId` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `externalReference` VARCHAR(191) NOT NULL,
  `orderId` VARCHAR(191) NULL,
  `paymentId` VARCHAR(191) NULL,
  `terminalId` VARCHAR(191) NOT NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  `currency` VARCHAR(191) NOT NULL DEFAULT 'MXN',
  `status` VARCHAR(191) NOT NULL DEFAULT 'creating',
  `statusDetail` VARCHAR(191) NULL,
  `saleId` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `paidAt` DATETIME(3) NULL,
  UNIQUE INDEX `point_payment_intents_externalReference_key`(`externalReference`),
  UNIQUE INDEX `point_payment_intents_orderId_key`(`orderId`),
  UNIQUE INDEX `point_payment_intents_saleId_key`(`saleId`),
  INDEX `point_payment_intents_organizationId_status_createdAt_idx`(`organizationId`, `status`, `createdAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `point_payment_intents_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `organizations`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
